### ISSUE TITLE
Add the section with working with YML file to understand how it works

### ISSUE THREAD

**Issue by OleksandrBaior** [Luxe-Quality/docusaurus_issues#11]
<div align="center"> 
<img <img src="https://static-00.iconduck.com/assets.00/cypress-icon-2048x2045-rgul477b.png" width="80"/>
 <h1> Example YML file for Cypress framework</h1>
</div>

Let's go through each line of this GitHub Actions configuration file:

### Header and Trigger Events

```yaml
name: Cypress Tests
```
- **name**: The name of the workflow, which will be displayed in the list of workflows on GitHub.

```yaml
on:
    workflow_dispatch:
```
- **workflow_dispatch**: Allows the workflow to be manually triggered from the GitHub interface.

```yaml
    push:
        branches: [master]
```
- **push**: Triggers the workflow when a push is made to the `master` branch.

```yaml
    pull_request:
        branches: [master]
```
- **pull_request**: Triggers the workflow when a pull request is created for the `master` branch.

#### Job "test"

```yaml
jobs:
    test:
        timeout-minutes: 60
```
- **test**: The name of the job. The job will be stopped if it runs for more than 60 minutes.

```yaml
        runs-on: ubuntu-latest
```
- **runs-on**: Specifies the virtual environment to run the job (`ubuntu-latest`).

```yaml
        name: E2E on Chrome
```
- **name**: Description of the job. The name that will appear in the logs.

```yaml
        steps:
```
- **steps**: List of steps to be executed in this job.

##### Steps of the "test" Job

```yaml
            - name: Checkout
              uses: actions/checkout@v4
```
- **name: Checkout**: Name of the step.
- **uses**: Uses the `actions/checkout@v4` action to clone the repository.

```yaml
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  browser: chrome
                  record: true
                  parallel: true
```
- **name: Cypress run**: Name of the step.
- **uses**: Uses the `cypress-io/github-action@v6` action to run Cypress tests.
- **with**: Parameters for configuring the action.
  - **browser**: Browser to use (`chrome`).
  - **record**: Record test results (`true`).
  - **parallel**: Run tests in parallel (`true`).

```yaml
              env:
                  group: 'UI-Chrome'
                  TZ: Europe/Warsaw
                  CYPRESS_ENV: Poland
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
- **env**: Environment variables.
  - **group**: Test group (`UI-Chrome`).
  - **TZ**: Timezone (`Europe/Warsaw`).
  - **CYPRESS_ENV**: Additional setting for Cypress (`Poland`).
  - **CYPRESS_RECORD_KEY**: Cypress record key, stored in the repository secrets.
  - **GITHUB_TOKEN**: GitHub token, stored in the repository secrets.

```yaml
            - name: Screenshots report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  if-no-files-found: ignore
```
- **name: Screenshots report**: Name of the step.
- **if: always()**: Always execute this step, even if previous steps failed.
- **uses**: Uses the `actions/upload-artifact@v4` action to upload artifacts.
- **with**: Parameters for configuring the action.
  - **name**: Name of the artifact (`cypress-screenshots`).
  - **path**: Path to the artifact (`cypress/screenshots`).
  - **if-no-files-found**: Ignore if no files are found (`ignore`).

```yaml
            - name: Video report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: cypress-videos
                  path: cypress/videos
                  if-no-files-found: ignore
```
- **name: Video report**: Name of the step.
- **if: always()**: Always execute this step, even if previous steps failed.
- **uses**: Uses the `actions/upload-artifact@v4` action to upload artifacts.
- **with**: Parameters for configuring the action.
  - **name**: Name of the artifact (`cypress-videos`).
  - **path**: Path to the artifact (`cypress/videos`).
  - **if-no-files-found**: Ignore if no files are found (`ignore`).

```yaml
            - name: Create cucumber-report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: cucumber-report
                  path: ./cucumber-report
                  retention-days: 15
```
- **name: Create cucumber-report**: Name of the step.
- **uses**: Uses the `actions/upload-artifact@v4` action to upload artifacts.
- **if: ${{ !cancelled() }}**: Execute this step if the workflow has not been cancelled.
- **with**: Parameters for configuring the action.
  - **name**: Name of the artifact (`cucumber-report`).
  - **path**: Path to the artifact (`./cucumber-report`).
  - **retention-days**: Number of days to retain the artifact (15).

#### Job "deploy"

```yaml
    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: always()
```
- **deploy**: The name of the job.
- **needs: test**: This job depends on the "test" job and will run after it.
- **runs-on**: Specifies the virtual environment to run the job (`ubuntu-latest`).
- **if: always()**: Always execute this job, even if previous jobs failed.

##### Steps of the "deploy" Job

```yaml
        steps:
            - name: Download cucumber report artifact
              if: always()
              uses: actions/download-artifact@v4
```
- **name: Download cucumber report artifact**: Name of the step.
- **if: always()**: Always execute this step.
- **uses**: Uses the `actions/download-artifact@v4` action to download artifacts.

```yaml
            - name: Display structure of downloaded files
              if: always()
              run: ls -R
```
- **name: Display structure of downloaded files**: Name of the step.
- **if: always()**: Always execute this step.
- **run**: Executes the command `ls -R` to display the structure of downloaded files.

```yaml
            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./cucumber-report
```
- **name: Deploy report to Github Pages**: Name of the step.
- **if: always()**: Always execute this step.
- **uses**: Uses the `peaceiris/actions-gh-pages@v2` action to deploy artifacts to GitHub Pages.
- **env**: Environment variables.
  - **PERSONAL_TOKEN**: GitHub token, stored in the repository secrets.
  - **PUBLISH_BRANCH**: Branch to publish to (`gh-pages`).
  - **PUBLISH_DIR**: Directory of files to publish (`./cucumber-report`).

<div align="center"> 
 <img src="https://raw.githubusercontent.com/github/explore/60cd2530141f67f07a947fa2d310c482e287e387/topics/playwright/playwright.png" width="80"/>
 <h1>Example YML file for Playwright framework</h1>
</div>

Let's go through each line of this GitHub Actions configuration file for running Playwright tests:

### Header and Trigger Events

```yaml
name: Playwright Tests
```
- **name**: The name of the workflow, displayed in the list of workflows on GitHub.

```yaml
on:
  workflow_dispatch:
```
- **workflow_dispatch**: Allows the workflow to be manually triggered from the GitHub interface.

```yaml
  push:
    branches: [main]
```
- **push**: Triggers the workflow when a push is made to the `main` branch.

```yaml
  pull_request:
    branches: [main]
```
- **pull_request**: Triggers the workflow when a pull request is created for the `main` branch.

#### Job "test"

```yaml
jobs:
  test:
    timeout-minutes: 60
```
- **test**: The name of the job. The job will be stopped if it runs for more than 60 minutes.

```yaml
    runs-on: ubuntu-latest
```
- **runs-on**: Specifies the virtual environment to run the job (`ubuntu-latest`).

```yaml
    steps:
```
- **steps**: List of steps to be executed in this job.

##### Steps of the "test" Job

```yaml
      - uses: actions/checkout@v4
```
- **uses**: Uses the `actions/checkout@v4` action to clone the repository.

```yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
```
- **uses**: Uses the `actions/setup-node@v4` action to set up Node.js.
- **with**: Parameters for configuring the action.
  - **node-version**: Specifies the Node.js version (`20`).

```yaml
      - name: Install dependencies
        run: npm ci
```
- **name: Install dependencies**: Name of the step.
- **run**: Runs the command `npm ci` to install dependencies based on the `package-lock.json`.

```yaml
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps 
```
- **name: Install Playwright Browsers**: Name of the step.
- **run**: Runs the command `npx playwright install --with-deps` to install Playwright browsers with dependencies.

```yaml
      - name: Run Playwright tests
        run: npx playwright test
```
- **name: Run Playwright tests**: Name of the step.
- **run**: Runs the command `npx playwright test` to execute the Playwright tests.

```yaml
      - name: Create playwright-report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: html-report
          path: reports
          retention-days: 30 
```
- **name: Create playwright-report**: Name of the step.
- **uses**: Uses the `actions/upload-artifact@v4` action to upload artifacts.
- **if: ${{ !cancelled() }}**: Execute this step if the workflow has not been cancelled.
- **with**: Parameters for configuring the action.
  - **name**: Name of the artifact (`html-report`).
  - **path**: Path to the artifact (`reports`).
  - **retention-days**: Number of days to retain the artifact (30).

```yaml
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
```
- **name: Get Allure history**: Name of the step.
- **uses**: Uses the `actions/checkout@v2` action to clone the repository.
- **if: always()**: Always execute this step, even if previous steps failed.
- **continue-on-error**: Continue execution even if this step fails.
- **with**: Parameters for configuring the action.
  - **ref**: The branch to checkout (`gh-pages`).
  - **path**: The path where the repository should be checked out (`gh-pages`).

```yaml
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: reports/allure-results
          allure_history: reports/allure-history
          keep_reports: 10
```
- **name: Allure Report action from marketplace**: Name of the step.
- **uses**: Uses the `simple-elf/allure-report-action@master` action to generate Allure reports.
- **if: always()**: Always execute this step, even if previous steps failed.
- **with**: Parameters for configuring the action.
  - **allure_results**: Path to the Allure results (`reports/allure-results`).
  - **allure_history**: Path to the Allure history (`reports/allure-history`).
  - **keep_reports**: Number of reports to keep (10).

```yaml
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: reports/allure-history
```
- **name: Deploy report to Github Pages**: Name of the step.
- **if: always()**: Always execute this step, even if previous steps failed.
- **uses**: Uses the `peaceiris/actions-gh-pages@v2` action to deploy artifacts to GitHub Pages.
- **env**: Environment variables.
  - **PERSONAL_TOKEN**: GitHub token, stored in the repository secrets.
  - **PUBLISH_BRANCH**: Branch to publish to (`gh-pages`).
  - **PUBLISH_DIR**: Directory of files to publish (`reports/allure-history`).
